version: 2
enable-beta-ecosystems: true
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: pub
    schedule:
      interval: weekly