version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly #keep this comment
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: monthly
