name: dependabot_gen
description: Dependabot gen is a Dart CLI tool to assist in the creation and maintenance of dependabot.yaml files in a project.
version: 1.2.0
repository: https://github.com/renancaraujo/dependabot_gen
issue_tracker: https://github.com/renancaraujo/dependabot_gen/issues
homepage: https://github.com/renancaraujo/dependabot_gen
documentation: https://github.com/renancaraujo/dependabot_gen
topics: [cli, automation, bash, code-generation, dependabot]
screenshots:
  - description: 'This screenshot shows a usage example of the dependabot_gen CLI tool.'
    path: doc/thumbnail.jpg

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  checked_yaml: ^2.0.3
  cli_completion: ^0.5.0
  collection: ^1.18.0
  equatable: ^2.0.5
  git: ^2.2.1
  json_annotation: ^4.8.1
  mason_logger: ">=0.2.5 <0.4.0"
  meta: ^1.11.0
  path: ^1.9.0
  pub_updater: ">=0.4.0 <0.6.0"
  recase: ^4.1.0
  yaml_edit: ^2.1.1
  yaml_writer: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.7
  build_verify: ^3.1.0
  build_version: ^2.1.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  test: ^1.24.6
  very_good_analysis: ">=5.1.0 <7.0.0"

executables:
  depgen:
  dependabot_gen:
