name: dependabot_gen
description: Keep your dependabot.yaml up to date
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  checked_yaml: ^2.0.3
  cli_completion: ^0.4.0
  git: ^2.2.1
  json_annotation: ^4.8.1
  mason_logger: ^0.2.5
  path: ^1.9.0
  pub_updater: ^0.4.0
  yaml_edit: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.7
  build_verify: ^3.1.0
  build_version: ^2.1.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^5.1.0

executables:
  depgen:
  dependabot_gen: depgen
