name: "Dependabot PR Formatter"
on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dependabot PR Formatter
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { pull_request: pr } = context.payload
            const newTitle = `build(deps): ${pr.title}`
            if (pr.title !== newTitle) {
              await github.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                title: newTitle
              })
            }